
language: node_js

before_install:
  - if [[ `npm -v` = 5* ]] && [[ `node -v` = v8* ]]; then npm install -g npm@4; fi

node_js:
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.10"

script:
  - npm run lint
  - npm test
